#!/usr/bin/env bash

sudo apt-add-repository ppa:ansible/ansible
sudo apt update -y
sudo apt install -y curl git software-properties-common ansible

sudo ansible-pull -U https://github.com/milos018/ansible.git